In [18]:
from pymatgen.ext.matproj import MPRester
import numpy

with MPRester("GlyakcTTvuJ54zVW") as m:
    results = m.query("mp-561619", ['cif'])[0]

In [19]:
a=open("local.cif",'w')
b=results.items()
for d,w in b:
    a.write(str(w))
a.close()

In [20]:
from pymatgen.io.cif import CifParser
parser = CifParser("local.cif")
structure = parser.get_structures(True)[0]
#les trois premières cases permettent d'obtenir la structure du matériau

In [21]:
c=structure.lattice
matrice=c.matrix
#stock dans des variables les vecteurs de base du réseau direct [d e f]
d=matrice[0]
e=matrice[1]
f=matrice[2]
print("les vecteurs de base du réseau direct :")
d,e,f

les vecteurs de base du réseau direct :


(array([ 1.83409575,  3.45302259, -0.97212894]),
 array([ 3.90989412, -0.        , -0.97212893]),
 array([-0.        , -0.        , -8.34884567]))

In [22]:
g=structure.lattice.reciprocal_lattice
matricer=g.matrix
#stock dans des variables les vecteurs de base du réseau réciproque [dr er fr]
dr=matricer[0]
er=matricer[1]
fr=matricer[2]
#print les vecteurs de base du réseau réciproque
print("les vecteurs de base du réseau réciproque :")
dr,er,fr

les vecteurs de base du réseau réciproque :


(array([ 0.        ,  1.81961894, -0.        ]),
 array([ 1.60699628, -0.85356669, -0.        ]),
 array([-0.1871166 , -0.11248589, -0.75258132]))

In [23]:
#verification des vecteurs de base
numpy.dot(matrice,(matricer.T)) #le produit doit être égal à 2pi*I

array([[6.28318531e+00, 0.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 6.28318531e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 6.28318531e+00]])

In [24]:
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

k=SpacegroupAnalyzer(SpacegroupAnalyzer(structure).get_primitive_standard_structure())

#donne le système cristallin
l=k.get_crystal_system()
#donne la maille 
nn = k.get_lattice_type()
#donne le groupe ponctuel
r=k.get_point_group_symbol()
#print (système cristallin, maille, groupe ponctuel)
print("le système cristallin est ",l)
print("la maille est ",nn)
print("le groupe ponctuel est ",r)


le système cristallin est  trigonal
la maille est  rhombohedral
le groupe ponctuel est  -3m
